version: '3.5'
services:
  php7:
    image: ${REGISTRY}/${PROJECT_NAME}/php7:${VERSION}
    restart: always
    env_file: 
      - ../config/${ENVIRONMENT}/php.env
    volumes:
      - backend_:/www
    networks:
      - tier_2
      - tier_log

  nginx:
    image: ${REGISTRY}/${PROJECT_NAME}/nginx:${VERSION}
    restart: always
    env_file: 
      - ../config/${ENVIRONMENT}/nginx.env
    volumes:
      - backend_:/www
    networks:
      - tier_2
      - tier_1
      - tier_log

  mysql:
    image: '${REGISTRY}/${PROJECT_NAME}/mariadb:${VERSION}'
    restart: always
    env_file:
      - ../config/${ENVIRONMENT}/mysql.env
    volumes:
      - 'mysql_:/var/lib/mysql'
    networks:
      - tier_2
      - tier_log
  
  # Memcached
  memcached:
    image: memcached:alpine
    networks:
      - tier_2
      - tier_log
  
  # VARNISH
  varnish:
    image: jonbaldie/varnish
    restart: always
    networks:
      - tier_2
      - tier_1
      - tier_log
  
  # REDIS
  redis:
    image: ${REGISTRY}/${PROJECT_NAME}/redis:${VERSION}
    volumes:
      - redis_:/data
    restart: always
    networks:
      - tier_2
      - tier_log
  
  # ElasticSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.3
    restart: always
    volumes:
      - elasticsearch_:/usr/share/elasticsearch/data
    networks:
      - tier_2
      - tier_log

volumes:
  redis_: null
  mysql_: null
  backend_: null
  elasticsearch_: null

networks:
  # Internet
  tier_0: null
  # Load balancer
  tier_1: 
    external:
      name: front-tier
  # Internal network
  tier_2: 
    internal: true
  # Dedicated to logging
  tier_log: null 
