version: '3.5'
services:
  ## PHP
  phplibs:
    image: ${REGISTRY}/${PROJECT_NAME}/phplibs:${VERSION}
    build:
      context: ../
      dockerfile: images/php/alpine/phplibs.dockerfile
  php7:
    image: ${REGISTRY}/${PROJECT_NAME}/php7:${VERSION}
    build:
      context: ../
      dockerfile: images/php/alpine/Dockerfile
      args:
        BASE: ${REGISTRY}/${PROJECT_NAME}/phplibs:${VERSION}
        ENVIRONMENT: ${ENVIRONMENT}

  ## NGINX
  nginxbase:
    image: ${REGISTRY}/${PROJECT_NAME}/nginxbase:${VERSION}
    build:
      context: ../
      dockerfile: images/nginx/base.dockerfile
  nginx:
    image: ${REGISTRY}/${PROJECT_NAME}/nginx:${VERSION}
    depends_on: 
      - nginxbase
    build:
      context: ../
      dockerfile: images/nginx/Dockerfile
      args:
        BASE: ${REGISTRY}/${PROJECT_NAME}/nginxbase:${VERSION}
        ENVIRONMENT: ${ENVIRONMENT}
  ## MySQL
  mysql:
    image: '${REGISTRY}/${PROJECT_NAME}/mariadb:${VERSION}'
    build:
      context: ../
      dockerfile: images/mysql/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
  
  ## REDIS
  redis:
    image: ${REGISTRY}/${PROJECT_NAME}/redis:${VERSION}
    build: 
      context: ../
      dockerfile: images/redis/Dockerfile