version: '3.5'
services:
  php7:
    volumes:
      - '../src/magento:/www'
    logging:
      driver: json-file
  mysql:
    ports:
      - '3306:3306'
    logging:
      driver: json-file
  nginx:
    volumes:
      - '../src/magento:/www'
    logging:
      driver: json-file
