version: '3.5'

services:
  php7:
    image: '${REGISTRY}/${PROJECT_NAME}/php7:${VERSION}'
    restart: unless-stopped
    expose:
      - '9000'
    volumes:
      - 'backend_:/www'
    env_file:
      - ../images/php/php.env
    networks:
      - tier_3
      - tier_log
  
  nginx:
    image: '${REGISTRY}/${PROJECT_NAME}/nginx:${VERSION}'
    restart: unless-stopped
    env_file:
      - ../images/nginx/proxy.env
    volumes:
      - 'backend_:/www'
    expose:
      - '443'
    networks:
      - tier_3
      - tier_log
      - tier_1
  
  # ElasticSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.3
    restart: unless-stopped
    volumes:
      - elasticsearch_:/usr/share/elasticsearch/data
    networks:
      - tier_3
      - tier_1
      - tier_log

volumes:
  redis_: null
  mysql_: null
  backend_: null
  elasticsearch_: null
networks:
  tier_0: null
  tier_1: 
    external:
      name: front-tier
  tier_2: null
  tier_3: null
  tier_log: null
